"""
Google Meet Integration Provider
==================================
Real implementation: Creates Google Meet links via Google Calendar API.

Meet links are generated by creating Calendar events with conferenceData.
Requires Google Calendar API v3 with calendar.events scope.

Authentication: Google OAuth 2.0 (shared with Google Calendar)
"""

import json
import uuid
from app.integrations.providers.base_provider import BaseIntegrationProvider
from app.integrations.credential_store import save_credentials, load_credentials, delete_credentials
from app.database.firestore import firestore_client
from app.utils.logger import log_info, log_error
from fastapi import HTTPException


class GoogleMeetProvider(BaseIntegrationProvider):

    INTEGRATION_ID = "int_gmeet"

    def _get_calendar_service(self, credentials: dict):
        try:
            from googleapiclient.discovery import build
            from app.integrations.oauth_helpers import build_google_credentials

            creds = build_google_credentials(
                access_token=credentials.get("access_token", ""),
                refresh_token=credentials.get("refresh_token", ""),
            )
            return build("calendar", "v3", credentials=creds, cache_discovery=False)
        except ImportError:
            raise HTTPException(status_code=500, detail="google-api-python-client not installed.")

    async def connect(self, workspace_id: str, payload: dict) -> dict:
        if payload.get("_oauth_completed"):
            connected_account = payload.get("connected_account", "Google Account")
            return await self._save_integration_state(workspace_id, payload, connected_account)

        creds = load_credentials(workspace_id, self.INTEGRATION_ID)
        if creds and creds.get("access_token"):
            connected_account = payload.get("connected_account") or creds.get("email", "Google Account")
            return await self._save_integration_state(workspace_id, payload, connected_account)

        log_info(f"Google Meet OAuth flow needed for workspace {workspace_id}")
        return {
            "id": self.INTEGRATION_ID,
            "workspace_id": workspace_id,
            "connected": False,
            "oauth_redirect": True,
            "oauth_url": None,
            "synced_agents": [],
            "last_sync": "Never",
            "health": 0,
            "config": {},
            "connected_account": None,
            "name": "Google Meet",
            "category": "Productivity",
            "description": "Create meeting links for live conversations.",
        }

    async def _save_integration_state(self, workspace_id: str, payload: dict, connected_account: str) -> dict:
        doc_ref = firestore_client.collection("integrations").document(f"{workspace_id}_{self.INTEGRATION_ID}")
        integration_data = {
            "id": self.INTEGRATION_ID,
            "workspace_id": workspace_id,
            "connected": True,
            "synced_agents": payload.get("synced_agents", []),
            "last_sync": "Just now",
            "health": 100,
            "config": payload.get("configuration", {}),
            "connected_account": connected_account,
        }
        doc_ref.set(integration_data, merge=True)
        log_info(f"Google Meet connected for workspace {workspace_id}")
        return integration_data

    async def disconnect(self, workspace_id: str) -> None:
        delete_credentials(workspace_id, self.INTEGRATION_ID)
        doc_ref = firestore_client.collection("integrations").document(f"{workspace_id}_{self.INTEGRATION_ID}")
        doc_ref.delete()
        log_info(f"Google Meet disconnected for workspace {workspace_id}")

    async def validate(self, config: dict, credentials: dict) -> bool:
        if not credentials.get("access_token"):
            return True
        try:
            service = self._get_calendar_service(credentials)
            service.calendarList().list(maxResults=1).execute()
            return True
        except Exception as e:
            log_error("Google Meet validation failed", exc=e)
            return False

    async def refresh(self, workspace_id: str) -> dict:
        creds = load_credentials(workspace_id, self.INTEGRATION_ID)
        if not creds or not creds.get("refresh_token"):
            return {}
        try:
            from app.integrations.oauth_helpers import refresh_google_token
            new_tokens = await refresh_google_token(creds["refresh_token"])
            creds["access_token"] = new_tokens["access_token"]
            save_credentials(workspace_id, self.INTEGRATION_ID, creds)
            log_info(f"Google Meet token refreshed for workspace {workspace_id}")
            return {"access_token": new_tokens["access_token"], "expires_in": new_tokens["expires_in"]}
        except Exception as e:
            log_error("Google Meet token refresh failed", exc=e)
            return {}

    async def execute(self, workspace_id: str, method: str, args: dict) -> str:
        creds = load_credentials(workspace_id, self.INTEGRATION_ID)
        if not creds or not creds.get("access_token"):
            return "Error: Google Meet is not connected. Please authenticate first."

        try:
            service = self._get_calendar_service(creds)
            method_lower = method.lower()

            if "create" in method_lower or "meeting" in method_lower or "schedule" in method_lower or "link" in method_lower:
                return await self._create_meet(service, args)
            elif "update" in method_lower:
                return await self._update_meeting(service, args)
            elif "cancel" in method_lower or "delete" in method_lower:
                return await self._cancel_meeting(service, args)

            return f"Error: Unknown method '{method}' on Google Meet. Available: create, update, cancel"

        except Exception as e:
            log_error(f"Google Meet execute failed for method {method}", exc=e)
            return f"Error: Google Meet action failed — {str(e)}"

    async def _create_meet(self, service, args: dict) -> str:
        import datetime

        summary = args.get("summary", args.get("title", "AI Agent Meeting"))
        start = args.get("start_time", args.get("start", ""))
        end = args.get("end_time", args.get("end", ""))
        attendees = args.get("attendees", [])
        description = args.get("description", "")
        timezone = args.get("timezone", "UTC")

        if not start:
            now = datetime.datetime.utcnow()
            start = now.isoformat() + "Z"
            end = (now + datetime.timedelta(hours=1)).isoformat() + "Z"
        if not end:
            from dateutil import parser as dtparser
            start_dt = dtparser.parse(start)
            end = (start_dt + datetime.timedelta(hours=1)).isoformat()

        request_id = uuid.uuid4().hex  # Unique request ID for idempotency

        event_body = {
            "summary": summary,
            "description": description,
            "start": {"dateTime": start, "timeZone": timezone},
            "end": {"dateTime": end, "timeZone": timezone},
            "conferenceData": {
                "createRequest": {
                    "requestId": request_id,
                    "conferenceSolutionKey": {"type": "hangoutsMeet"},
                }
            },
        }
        if attendees:
            event_body["attendees"] = [{"email": a} for a in attendees]

        result = service.events().insert(
            calendarId="primary",
            body=event_body,
            conferenceDataVersion=1,
        ).execute()

        meet_link = result.get("hangoutLink", "")
        conference_id = result.get("conferenceData", {}).get("conferenceId", "")

        return (
            f"Google Meet session created: '{summary}'\n"
            f"Meet Link: {meet_link}\n"
            f"Event ID: {result.get('id')}\n"
            f"Conference ID: {conference_id}\n"
            f"Calendar Event: {result.get('htmlLink', '')}"
        )

    async def _update_meeting(self, service, args: dict) -> str:
        event_id = args.get("event_id")
        if not event_id:
            return "Error: event_id is required to update a meeting."

        event = service.events().get(calendarId="primary", eventId=event_id).execute()
        if "summary" in args:
            event["summary"] = args["summary"]
        if "description" in args:
            event["description"] = args["description"]
        if "start_time" in args:
            event["start"]["dateTime"] = args["start_time"]
        if "end_time" in args:
            event["end"]["dateTime"] = args["end_time"]

        result = service.events().update(calendarId="primary", eventId=event_id, body=event).execute()
        meet_link = result.get("hangoutLink", "")
        return f"Successfully updated meeting '{event_id}'. Meet Link: {meet_link}"

    async def _cancel_meeting(self, service, args: dict) -> str:
        event_id = args.get("event_id")
        if not event_id:
            return "Error: event_id is required to cancel a meeting."

        service.events().delete(calendarId="primary", eventId=event_id).execute()
        return f"Successfully cancelled Google Meet session '{event_id}'."

    def capabilities(self) -> list:
        return ["Create meeting links", "Add invite details", "Update scheduled calls"]
